version: '3.8'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/v2ray/config.json
    ports:
      - '1080:1080'
      - '1087:1087'
    expose:
      - '1080'
      - '1087'
    networks:
      - default
networks:
  default:
    name: 'v2ray'
    driver: bridge
