version: '3.8'

services:
  v2ray:
    image: kuqoi/v2ray:4
    container_name: v2ray
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/v2ray/config.json
    ports:
      - '26825:37192'
      - '29875:1234'
    expose:
      - '26825'
      - '29875'
    networks:
      - default
networks:
  default:
    name: 'v2ray'
    driver: bridge
