version: '3.8'

services:
  v2ray:
    image: kuqoi/v2ray:4
    container_name: v2ray
    restart: unless-stopped
    environment:
      - V2RAY_VMESS_AEAD_FORCED=false
    volumes:
      - ./config.json:/etc/v2ray/config.json
    ports:
      - '28901:37192'
    expose:
      - '28901'
    networks:
      - default
networks:
  default:
    name: 'v2ray'
    driver: bridge
